#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$DIR"

rm data_out/*

/usr/local/bin/node "$DIR"/bin/science2.js data_in data_out bin/AssayInfo.txt bin/Ots_GTseq95_ProbeSeqs_v2.csv


