#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

data_in="$1"
data_out="$2"

if [ "$data_out" != "" ] ; then
	rm "$data_out/"*
fi

echo Start: `date`

/usr/local/bin/node ./bin/science3.js "$data_in"  "$data_out" steelhead

echo Finish: `date`


